# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'takip.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(681, 256)
        self.tablo = QtWidgets.QTableWidget(Form)
        self.tablo.setGeometry(QtCore.QRect(0, 0, 641, 191))
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(5)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(4, item)
        self.ilerleButon = QtWidgets.QPushButton(Form)
        self.ilerleButon.setGeometry(QtCore.QRect(230, 200, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ilerleButon.setFont(font)
        self.ilerleButon.setObjectName("ilerleButon")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "İlerleme"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "1.gün"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "2.gün"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("Form", "3.gün"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("Form", "4.gün"))
        item = self.tablo.horizontalHeaderItem(4)
        item.setText(_translate("Form", "5.gün"))
        self.ilerleButon.setText(_translate("Form", "Başla"))
